const dbData = [
  { "id": 1, "name": "Google", "salary": "₹22 - 40 LPA", "location": "Bengaluru", "role": "Software Engineer", "type": "Product", "url": "https://www.google.com/about/careers/" },
  { "id": 2, "name": "Microsoft", "salary": "₹22 - 45 LPA", "location": "Bengaluru", "role": "Software Engineer", "type": "Product", "url": "https://careers.microsoft.com/" },
  { "id": 3, "name": "Zoho", "salary": "₹8 - 12 LPA", "location": "Chennai", "role": "Member Tech Staff", "type": "Product", "url": "https://www.zoho.com/careers/" },
  { "id": 4, "name": "Freshworks", "salary": "₹10 - 14 LPA", "location": "Chennai", "role": "Software Engineer", "type": "Product", "url": "https://www.freshworks.com/company/careers/" },
  { "id": 5, "name": "Flipkart", "salary": "₹26 - 32 LPA", "location": "Bengaluru", "role": "Data Scientist, SDE-1", "type": "Product", "url": "https://www.flipkartcareers.com/" },
  { "id": 6, "name": "PayPal", "salary": "₹15 - 24 LPA", "location": "Chennai / Bengaluru", "role": "Risk AI, Data Science", "type": "Fintech", "url": "https://careers.pypl.com/home/" },
  { "id": 7, "name": "Amazon", "salary": "₹25 - 45 LPA", "location": "Bengaluru / Chennai", "role": "SDE - I", "type": "Product", "url": "https://www.amazon.jobs/" },
  { "id": 8, "name": "TCS (Prime/Digital)", "salary": "₹7 - 11.5 LPA", "location": "Pan-India", "role": "System Engineer", "type": "Service", "url": "https://www.tcs.com/careers" },
  { "id": 9, "name": "Infosys (SP/DSE)", "salary": "₹6.5 - 12 LPA", "location": "Pan-India", "role": "Specialist Programmer", "type": "Service", "url": "https://www.infosys.com/careers/" },
  { "id": 10, "name": "KLA Tencor", "salary": "₹18 - 22 LPA", "location": "Chennai", "role": "Deep Tech, AI/HPC", "type": "DeepTech", "url": "https://www.kla.com/careers" },
  { "id": 11, "name": "Chargebee", "salary": "₹16 - 20 LPA", "location": "Chennai", "role": "Product Dev", "type": "SaaS", "url": "https://careers.chargebee.com/" },
  { "id": 12, "name": "Cred", "salary": "₹20 - 30 LPA", "location": "Bengaluru", "role": "Backend", "type": "Fintech", "url": "https://careers.cred.club/" },
  { "id": 13, "name": "Swiggy", "salary": "₹18 - 24 LPA", "location": "Bengaluru", "role": "SDE - I", "type": "Product", "url": "https://careers.swiggy.com/" },
  { "id": 14, "name": "Zomato", "salary": "₹20 - 28 LPA", "location": "Bengaluru", "role": "SDE - I", "type": "Product", "url": "https://www.zomato.com/careers" },
  { "id": 15, "name": "Uber", "salary": "₹35 - 40 LPA", "location": "Bengaluru", "role": "SDE - I", "type": "Product", "url": "https://www.uber.com/us/en/careers/" },
  { "id": 16, "name": "Samsung R&D", "salary": "₹16 - 22 LPA", "location": "Bengaluru / Chennai", "role": "AI, On-Device ML", "type": "DeepTech", "url": "https://research.samsung.com/sri-b" },
  { "id": 17, "name": "Salesforce", "salary": "₹25 - 35 LPA", "location": "Bengaluru", "role": "MTS", "type": "SaaS", "url": "https://www.salesforce.com/company/careers/" },
  { "id": 18, "name": "Atlassian", "salary": "₹25 - 50 LPA", "location": "Bengaluru (Remote)", "role": "SDE - I", "type": "SaaS", "url": "https://www.atlassian.com/company/careers" },
  { "id": 19, "name": "Rocketlane", "salary": "₹14 - 18 LPA", "location": "Chennai", "role": "SaaS Product Dev", "type": "SaaS", "url": "https://careers.kula.ai/rocketlane" },
  { "id": 20, "name": "Mad Street Den", "salary": "₹12 - 15 LPA", "location": "Chennai", "role": "Computer Vision", "type": "AI", "url": "https://www.madstreetden.com/careers/" },
  { "id": 21, "name": "Uniphore", "salary": "₹12 - 18 LPA", "location": "Chennai", "role": "Conversational AI", "type": "AI", "url": "https://www.uniphore.com/careers/" },
  { "id": 22, "name": "Yubi", "salary": "₹12 - 16 LPA", "location": "Chennai", "role": "Fintech SDE", "type": "Fintech", "url": "https://www.go-yubi.com/careers" },
  { "id": 23, "name": "Kissflow", "salary": "₹8 - 12 LPA", "location": "Chennai", "role": "Product Engineer", "type": "SaaS", "url": "https://kissflow.com/careers/" },
  { "id": 24, "name": "Walmart Global Tech", "salary": "₹18 - 26 LPA", "location": "Bengaluru / Chennai", "role": "SDE - III", "type": "Product", "url": "https://careers.walmart.com/technology" },
  { "id": 25, "name": "Cisco", "salary": "₹14 - 18 LPA", "location": "Bengaluru / Chennai", "role": "Software Engineer", "type": "DeepTech", "url": "https://jobs.cisco.com/" },
  { "id": 26, "name": "JPMorgan Chase", "salary": "₹12 - 18 LPA", "location": "Bengaluru", "role": "Software Engineer", "type": "Fintech", "url": "https://careers.jpmorgan.com/" },
  { "id": 27, "name": "Wells Fargo", "salary": "₹10 - 14 LPA", "location": "Bengaluru / Chennai", "role": "Program Associate", "type": "Fintech", "url": "https://www.wellsfargojobs.com/" },
  { "id": 28, "name": "Citi", "salary": "₹10 - 15 LPA", "location": "Chennai / Bengaluru", "role": "Tech Analyst", "type": "Fintech", "url": "https://jobs.citi.com/" },
  { "id": 29, "name": "Standard Chartered", "salary": "₹8 - 12 LPA", "location": "Chennai / Bengaluru", "role": "Developer", "type": "Fintech", "url": "https://www.sc.com/en/global-careers/" },
  { "id": 30, "name": "LatentView Analytics", "salary": "₹8 - 11 LPA", "location": "Chennai", "role": "Data Analyst", "type": "Data", "url": "https://www.latentview.com/career/" },
  { "id": 31, "name": "Tiger Analytics", "salary": "₹8 - 12 LPA", "location": "Chennai", "role": "Data Scientist", "type": "Data", "url": "https://www.tigeranalytics.com/about-us/current-openings/" },
  { "id": 32, "name": "Renault Nissan", "salary": "₹5 - 7 LPA", "location": "Chennai", "role": "GET (Software)", "type": "AutoTech", "url": "https://www.nissanmotor.jobs/careerarea" },
  { "id": 33, "name": "Ford Motors", "salary": "₹6 - 8 LPA", "location": "Chennai", "role": "IT Engineer", "type": "AutoTech", "url": "https://corporate.ford.com/careers.html" },
  { "id": 34, "name": "Verizon", "salary": "₹6 - 9 LPA", "location": "Chennai", "role": "Software Engineer", "type": "Service", "url": "https://www.verizon.com/about/careers" },
  { "id": 35, "name": "Comcast", "salary": "₹7 - 10 LPA", "location": "Chennai", "role": "Engineer 1", "type": "Service", "url": "https://jobs.comcast.com/" },
  { "id": 36, "name": "Fireflies.ai", "salary": "₹33 - 41 LPA", "location": "Remote", "role": "AI Engineer", "type": "AI", "url": "https://fireflies.ai/careers" },
  { "id": 37, "name": "Automattic", "salary": "₹35 - 45 LPA", "location": "Remote", "role": "Code Wrangler", "type": "Product", "url": "https://automattic.com/work-with-us/" },
  { "id": 38, "name": "Turing", "salary": "₹16 - 33 LPA", "location": "Remote", "role": "AI/ML Engineer", "type": "Platform", "url": "https://www.turing.com/jobs" },
  { "id": 39, "name": "Accenture", "salary": "₹6 - 12 LPA", "location": "Pan-India", "role": "Packaged App Dev", "type": "Service", "url": "https://www.accenture.com/in-en/careers" },
  { "id": 40, "name": "Wipro", "salary": "₹6 - 10 LPA", "location": "Pan-India", "role": "Project Engineer", "type": "Service", "url": "https://careers.wipro.com/" },
  { "id": 41, "name": "LTIMindtree", "salary": "₹5 - 8 LPA", "location": "Bengaluru / Chennai", "role": "Graduate Engineer", "type": "Service", "url": "https://www.ltimindtree.com/careers/" },
  { "id": 42, "name": "Capgemini", "salary": "₹5.75 - 7.5 LPA", "location": "Bengaluru / Chennai", "role": "Analyst", "type": "Service", "url": "https://www.capgemini.com/careers/" },
  { "id": 43, "name": "Virtusa", "salary": "₹5 - 7 LPA", "location": "Chennai / Bengaluru", "role": "Full Stack Engineer", "type": "Service", "url": "https://www.virtusa.com/careers" },
  { "id": 44, "name": "HCLTech", "salary": "₹6 - 10 LPA", "location": "Chennai / Noida", "role": "Product Role", "type": "Service", "url": "https://www.hcltech.com/careers" },
  { "id": 45, "name": "Hexaware", "salary": "₹5 - 6 LPA", "location": "Chennai", "role": "PGET (Mavericks)", "type": "Service", "url": "https://jobs.hexaware.com/" },
  { "id": 46, "name": "Mr. Cooper", "salary": "₹6 - 9 LPA", "location": "Chennai", "role": "Software Engineer", "type": "Fintech", "url": "https://www.mrcooper.com/careers" },
  { "id": 47, "name": "Caterpillar", "salary": "₹6 - 9 LPA", "location": "Chennai", "role": "IT Analyst", "type": "AutoTech", "url": "https://www.caterpillar.com/en/careers.html" },
  { "id": 48, "name": "Athenahealth", "salary": "₹7 - 10 LPA", "location": "Chennai / Bengaluru", "role": "Software Engineer", "type": "HealthTech", "url": "https://www.athenahealth.com/careers" },
  { "id": 49, "name": "Temenos", "salary": "₹6 - 9 LPA", "location": "Chennai / Bengaluru", "role": "Product Developer", "type": "Fintech", "url": "https://www.temenos.com/careers/" },
  { "id": 50, "name": "Kaar Tech", "salary": "₹6 - 8 LPA", "location": "Chennai", "role": "SAP Consultant", "type": "Service", "url": "https://www.kaartech.com/career/" },
  { "id": 51, "name": "Ramco Systems", "salary": "₹5 - 7 LPA", "location": "Chennai", "role": "Product Developer", "type": "SaaS", "url": "https://www.ramco.com/careers" },
  { "id": 52, "name": "Intellect Design", "salary": "₹5 - 8 LPA", "location": "Chennai", "role": "Product Engineer", "type": "Fintech", "url": "https://www.intellectdesign.com/careers/" },
  { "id": 53, "name": "Sify Tech", "salary": "₹5 - 7 LPA", "location": "Chennai", "role": "Network Engineer", "type": "Service", "url": "https://www.sifytechnologies.com/careers/" },
  { "id": 54, "name": "Tata Elxsi", "salary": "₹5 - 7 LPA", "location": "Bengaluru / Chennai", "role": "Embedded Engineer", "type": "DeepTech", "url": "https://www.tataelxsi.com/careers" },
  { "id": 55, "name": "PhonePe", "salary": "₹22 - 32 LPA", "location": "Bengaluru", "role": "SDE", "type": "Fintech", "url": "https://www.phonepe.com/careers/" },
  { "id": 56, "name": "Razorpay", "salary": "₹20 - 26 LPA", "location": "Bengaluru", "role": "SDE", "type": "Fintech", "url": "https://razorpay.com/jobs/" },
  { "id": 57, "name": "Postman", "salary": "₹20 - 28 LPA", "location": "Bengaluru", "role": "SDE", "type": "Product", "url": "https://www.postman.com/careers/" },
  { "id": 58, "name": "InMobi / Glance", "salary": "₹18 - 24 LPA", "location": "Bengaluru", "role": "Data Scientist", "type": "AdTech", "url": "https://www.inmobi.com/company/careers/" },
  { "id": 59, "name": "Zeta Suite", "salary": "₹22 - 28 LPA", "location": "Bengaluru", "role": "SDE", "type": "Fintech", "url": "https://www.zeta.tech/careers/" },
  { "id": 60, "name": "Meesho", "salary": "₹20 - 30 LPA", "location": "Bengaluru", "role": "SDE", "type": "Product", "url": "https://www.meesho.io/jobs" },
  { "id": 61, "name": "Groww", "salary": "₹18 - 24 LPA", "location": "Bengaluru", "role": "SDE", "type": "Fintech", "url": "https://groww.in/careers" },
  { "id": 62, "name": "Zerodha", "salary": "₹15 - 20 LPA", "location": "Bengaluru", "role": "Software Engineer", "type": "Fintech", "url": "https://zerodha.com/careers" },
  { "id": 63, "name": "Cure.fit", "salary": "₹18 - 24 LPA", "location": "Bengaluru", "role": "SDE", "type": "HealthTech", "url": "https://www.cure.fit/careers" },
  { "id": 64, "name": "Goldman Sachs", "salary": "₹20 - 24 LPA", "location": "Bengaluru", "role": "Analyst", "type": "Fintech", "url": "https://www.goldmansachs.com/careers/" },
  { "id": 65, "name": "Intuit", "salary": "₹20 - 28 LPA", "location": "Bengaluru", "role": "SDE", "type": "Fintech", "url": "https://www.intuit.com/careers/" },
  { "id": 66, "name": "Target", "salary": "₹12 - 16 LPA", "location": "Bengaluru", "role": "Engineer", "type": "Product", "url": "https://corporate.target.com/careers" },
  { "id": 67, "name": "SAP Labs", "salary": "₹10 - 16 LPA", "location": "Bengaluru", "role": "Developer Associate", "type": "SaaS", "url": "https://www.sap.com/careers" },
  { "id": 68, "name": "Oracle", "salary": "₹10 - 16 LPA", "location": "Bengaluru / Chennai", "role": "MTS", "type": "SaaS", "url": "https://www.oracle.com/careers/" },
  { "id": 69, "name": "Shell", "salary": "₹10 - 14 LPA", "location": "Bengaluru / Chennai", "role": "IT Engineer", "type": "DeepTech", "url": "https://jobs.shell.com/" },
  { "id": 70, "name": "Mercedes Benz", "salary": "₹8 - 12 LPA", "location": "Bengaluru", "role": "GET / PGET", "type": "AutoTech", "url": "https://group.mercedes-benz.com/careers/" },
  { "id": 71, "name": "Bosch (R&D)", "salary": "₹7 - 10 LPA", "location": "Bengaluru", "role": "Software Engineer", "type": "DeepTech", "url": "https://www.bosch.in/careers/" },
  { "id": 72, "name": "Siemens", "salary": "₹7 - 10 LPA", "location": "Bengaluru", "role": "R&D Engineer", "type": "DeepTech", "url": "https://www.siemens.com/careers" },
  { "id": 73, "name": "Philips", "salary": "₹9 - 12 LPA", "location": "Bengaluru", "role": "Software Engineer", "type": "HealthTech", "url": "https://www.careers.philips.com/global/en" },
  { "id": 74, "name": "GE Healthcare", "salary": "₹9 - 12 LPA", "location": "Bengaluru", "role": "Edison Engineer", "type": "HealthTech", "url": "https://jobs.gecareers.com/" },
  { "id": 75, "name": "Honeywell", "salary": "₹8 - 12 LPA", "location": "Bengaluru", "role": "Software Engineer", "type": "DeepTech", "url": "https://careers.honeywell.com/" },
  { "id": 76, "name": "Qualcomm", "salary": "₹12 - 18 LPA", "location": "Bengaluru / Chennai", "role": "Interim Eng.", "type": "DeepTech", "url": "https://qualcomm.com/careers" },
  { "id": 77, "name": "Ericsson", "salary": "₹6 - 9 LPA", "location": "Bengaluru / Chennai", "role": "R&D Engineer", "type": "DeepTech", "url": "https://www.ericsson.com/en/careers" },
  { "id": 78, "name": "Bank of America", "salary": "₹8 - 12 LPA", "location": "Chennai", "role": "Software Engineer", "type": "Fintech", "url": "https://careers.bankofamerica.com/" },
  { "id": 79, "name": "Amadeus", "salary": "₹7 - 10 LPA", "location": "Bengaluru", "role": "Software Engineer", "type": "SaaS", "url": "https://amadeus.com/en/careers/locations/bengaluru" },
  { "id": 80, "name": "Maersk (GSC)", "salary": "₹7 - 10 LPA", "location": "Bengaluru / Chennai", "role": "Software Engineer", "type": "Service", "url": "https://www.maersk.com/careers" },
  { "id": 81, "name": "DE Shaw", "salary": "₹30 - 38 LPA", "location": "Bengaluru", "role": "Member Technical", "type": "Fintech", "url": "https://www.deshawindia.com/careers" },
  { "id": 82, "name": "Media.net", "salary": "₹25 - 30 LPA", "location": "Bengaluru", "role": "SDE", "type": "AdTech", "url": "https://careers.media.net/" },
  { "id": 83, "name": "Arcesium", "salary": "₹30 - 36 LPA", "location": "Bengaluru", "role": "SDE", "type": "Fintech", "url": "https://www.arcesium.com/careers/" },
  { "id": 84, "name": "Juniper Networks", "salary": "₹15 - 20 LPA", "location": "Bengaluru", "role": "Software Engineer", "type": "DeepTech", "url": "https://careers.juniper.net/" },
  { "id": 85, "name": "Citrix (Cloud Software Group)", "salary": "₹20 - 26 LPA", "location": "Bengaluru", "role": "SDE", "type": "SaaS", "url": "https://careers.cloud.com/" },
  { "id": 86, "name": "Morgan Stanley", "salary": "₹12 - 18 LPA", "location": "Bengaluru", "role": "Technology Analyst", "type": "Fintech", "url": "https://www.morganstanley.com/careers/career-opportunities-search?opportunity=sg" },
  { "id": 87, "name": "Barclays", "salary": "₹10 - 14 LPA", "location": "Chennai (Pune majorly)", "role": "BA4 Developer", "type": "Fintech", "url": "https://home.barclays/careers/" },
  { "id": 88, "name": "Fidelity Investments", "salary": "₹10 - 14 LPA", "location": "Bengaluru / Chennai", "role": "Software Engineer", "type": "Fintech", "url": "https://jobs.fidelity.com/" },
  { "id": 89, "name": "NatWest Group", "salary": "₹9 - 12 LPA", "location": "Chennai / Bengaluru", "role": "Software Engineer", "type": "Fintech", "url": "https://jobs.natwestgroup.com/" },
  { "id": 90, "name": "BNY", "salary": "₹10 - 15 LPA", "location": "Chennai", "role": "SDE", "type": "Fintech", "url": "https://bnymellon.eightfold.ai/careers" },
  { "id": 91, "name": "Societe Generale", "salary": "₹10 - 14 LPA", "location": "Bengaluru", "role": "Software Engineer", "type": "Fintech", "url": "https://careers.societegenerale.com/" },
  { "id": 92, "name": "Visa", "salary": "₹14 - 18 LPA", "location": "Bengaluru", "role": "Software Engineer", "type": "Fintech", "url": "https://www.visa.co.in/careers.html" },
  { "id": 93, "name": "Mastercard", "salary": "₹10 - 14 LPA", "location": "Bengaluru", "role": "Software Engineer", "type": "Fintech", "url": "https://www.mastercard.us/en-us/vision/who-we-are/careers.html" },
  { "id": 94, "name": "American Express", "salary": "₹12 - 16 LPA", "location": "Bengaluru", "role": "Engineer", "type": "Fintech", "url": "https://www.americanexpress.com/en-us/careers/" },
  { "id": 95, "name": "M2P Fintech", "salary": "₹10 - 14 LPA", "location": "Chennai", "role": "SDE", "type": "Fintech", "url": "https://m2pfintech.com/careers/" },
  { "id": 96, "name": "Kaleidofin", "salary": "₹10 - 15 LPA", "location": "Chennai", "role": "Data Scientist / SDE", "type": "Fintech", "url": "https://kaleidofin.com/careers/" },
  { "id": 97, "name": "Crayon Data", "salary": "₹8 - 12 LPA", "location": "Chennai", "role": "Data Scientist", "type": "Data", "url": "https://www.crayondata.com/careers/" },
  { "id": 98, "name": "Fractal Analytics", "salary": "₹9 - 14 LPA", "location": "Bengaluru / Chennai", "role": "Imagineer", "type": "Data", "url": "https://fractal.ai/careers/" },
  { "id": 99, "name": "Mu Sigma", "salary": "₹7 - 10 LPA", "location": "Bengaluru", "role": "Decision Scientist", "type": "Data", "url": "https://www.mu-sigma.com/careers" },
  { "id": 100, "name": "ZS Associates", "salary": "₹8 - 13 LPA", "location": "Bengaluru", "role": "Business Tech Analyst", "type": "Service", "url": "https://www.zs.com/careers" },
  { "id": 101, "name": "HashedIn (Deloitte)", "salary": "₹8 - 12 LPA", "location": "Bengaluru", "role": "SDE - I", "type": "Service", "url": "https://hashedin.com/careers/" },
  { "id": 102, "name": "Publicis Sapient", "salary": "₹8 - 12 LPA", "location": "Bengaluru", "role": "Jr. Associate (L1)", "type": "Service", "url": "https://careers.publicissapient.com/" },
  { "id": 103, "name": "Thoughtworks", "salary": "₹9 - 11 LPA", "location": "Bengaluru / Chennai", "role": "Application Developer", "type": "Service", "url": "https://www.thoughtworks.com/careers" },
  { "id": 104, "name": "IBM (ISL/Labs)", "salary": "₹7 - 12 LPA", "location": "Bengaluru", "role": "Software Developer", "type": "Product", "url": "https://www.ibm.com/careers" },
  { "id": 105, "name": "Akamai", "salary": "₹12 - 16 LPA", "location": "Bengaluru", "role": "SDE", "type": "DeepTech", "url": "https://www.akamai.com/careers" },
  { "id": 106, "name": "Broadcom (VMware)", "salary": "₹12 - 20 LPA", "location": "Bengaluru", "role": "MTS", "type": "DeepTech", "url": "https://www.broadcom.com/company/careers" },
  { "id": 107, "name": "Continental", "salary": "₹6 - 9 LPA", "location": "Bengaluru", "role": "Software Engineer", "type": "AutoTech", "url": "https://www.continental.com/en/career/" },
  { "id": 108, "name": "ABB", "salary": "₹7 - 10 LPA", "location": "Bengaluru", "role": "R&D Engineer", "type": "DeepTech", "url": "https://careers.abb/" },
  { "id": 109, "name": "Nokia", "salary": "₹7 - 10 LPA", "location": "Bengaluru / Chennai", "role": "R&D Engineer", "type": "DeepTech", "url": "https://www.nokia.com/about-us/careers/" },
  { "id": 110, "name": "Samsung Semiconductor", "salary": "₹12 - 16 LPA", "location": "Bengaluru", "role": "Engineer", "type": "DeepTech", "url": "https://semiconductor.samsung.com/about-us/careers/jobs/?region=india" },
  { "id": 111, "name": "Cognizant", "salary": "₹6.5 - 7.5 LPA", "location": "All Locations", "role": "GenC Next", "type": "Service", "url": "https://careers.cognizant.com/global/en" },
  { "id": 112, "name": "KPIT Technologies", "salary": "₹5 - 6.5 LPA", "location": "Bengaluru", "role": "Software Engineer", "type": "AutoTech", "url": "https://www.kpit.com/careers/" },
  { "id": 113, "name": "L&T Technology Services", "salary": "₹5 - 6 LPA", "location": "Chennai / Bengaluru", "role": "Engineer", "type": "Service", "url": "https://www.ltts.com/careers" },
  { "id": 114, "name": "Persistent Systems", "salary": "₹5 - 7 LPA", "location": "Bengaluru", "role": "Software Engineer", "type": "Service", "url": "https://www.persistent.com/careers/" },
  { "id": 115, "name": "Sonata Software", "salary": "₹5 - 7 LPA", "location": "Bengaluru", "role": "Software Engineer", "type": "Service", "url": "https://www.sonata-software.com/careers" },
  { "id": 116, "name": "Sasken Technologies", "salary": "₹5 - 7 LPA", "location": "Bengaluru / Chennai", "role": "R&D Engineer", "type": "DeepTech", "url": "https://www.sasken.com/careers" },
  { "id": 117, "name": "Happiest Minds", "salary": "₹5.5 - 7 LPA", "location": "Bengaluru", "role": "Software Engineer", "type": "Service", "url": "https://www.happiestminds.com/careers/" },
  { "id": 118, "name": "Tally Solutions", "salary": "₹7 - 10 LPA", "location": "Bengaluru", "role": "Software Engineer", "type": "Product", "url": "https://tallysolutions.com/careers/" },
  { "id": 119, "name": "Subex", "salary": "₹5 - 7 LPA", "location": "Bengaluru", "role": "Support / Dev", "type": "Service", "url": "https://www.subex.com/careers/" },
  { "id": 120, "name": "Tejas Networks", "salary": "₹7 - 10 LPA", "location": "Bengaluru", "role": "R&D Engineer", "type": "DeepTech", "url": "https://www.tejasnetworks.com/careers.php" },
  { "id": 121, "name": "Quest Global", "salary": "₹4.5 - 6 LPA", "location": "Bengaluru", "role": "Software Engineer", "type": "Service", "url": "https://www.quest-global.com/careers/" },
  { "id": 122, "name": "Brillio", "salary": "₹5 - 7 LPA", "location": "Bengaluru", "role": "Software Engineer", "type": "Service", "url": "https://www.brillio.com/careers/" },
  { "id": 123, "name": "ITC Infotech", "salary": "₹4.5 - 6 LPA", "location": "Bengaluru", "role": "Software Engineer", "type": "Service", "url": "https://jobs.itcinfotech.com/itcinfotech/jobslist" },
  { "id": 124, "name": "Eurofins IT", "salary": "₹6 - 8 LPA", "location": "Bengaluru", "role": "Software Engineer", "type": "HealthTech", "url": "https://careers.eurofins.com/" },
  { "id": 125, "name": "Sabre", "salary": "₹8 - 12 LPA", "location": "Bengaluru", "role": "Software Engineer", "type": "SaaS", "url": "https://www.sabre.com/careers/" },
  { "id": 126, "name": "Alstom", "salary": "₹6 - 9 LPA", "location": "Bengaluru", "role": "Signaling / SW Eng", "type": "AutoTech", "url": "https://www.alstom.com/careers" },
  { "id": 127, "name": "Wabco (ZF)", "salary": "₹6 - 9 LPA", "location": "Chennai", "role": "Embedded Eng", "type": "AutoTech", "url": "https://www.zf.com/mobile/en/careers/careers.html" },
  { "id": 128, "name": "Danfoss", "salary": "₹6 - 8 LPA", "location": "Chennai", "role": "Engineer", "type": "DeepTech", "url": "https://www.danfoss.com/en/about-danfoss/careers/" },
  { "id": 129, "name": "Saint-Gobain", "salary": "₹5.5 - 7 LPA", "location": "Chennai", "role": "IT / GET", "type": "Service", "url": "https://www.saint-gobain.com/en/careers" },
  { "id": 133, "name": "GitLab", "salary": "₹20 - 40 LPA", "location": "Remote", "role": "DevOps", "type": "Product", "url": "https://about.gitlab.com/jobs/" },
  { "id": 134, "name": "Supabase", "salary": "₹20 - 40 LPA", "location": "Remote", "role": "SDE", "type": "Product", "url": "https://supabase.com/careers" },
  { "id": 135, "name": "Hasura", "salary": "₹20 - 35 LPA", "location": "Bengaluru / Remote", "role": "SDE", "type": "Product", "url": "https://hasura.io/careers/" },
  { "id": 136, "name": "Grafana Labs", "salary": "₹20 - 40 LPA", "location": "Remote", "role": "SDE", "type": "Product", "url": "https://grafana.com/about/careers/" },
  { "id": 137, "name": "Canonical", "salary": "₹15 - 35 LPA", "location": "Remote", "role": "SDE", "type": "Product", "url": "https://canonical.com/careers" },
  { "id": 138, "name": "Polygon (Matic)", "salary": "₹20 - 50 LPA", "location": "Remote", "role": "Blockchain Dev", "type": "Fintech", "url": "https://polygon.technology/careers" },
  { "id": 139, "name": "Airmeet", "salary": "₹15 - 25 LPA", "location": "Remote", "role": "SDE", "type": "Product", "url": "https://www.airmeet.com/hub/career/" },
  { "id": 140, "name": "HackerRank", "salary": "₹18 - 28 LPA", "location": "Remote / Blr", "role": "SDE", "type": "Product", "url": "https://www.hackerrank.com/careers/" },
  { "id": 141, "name": "Innovaccer", "salary": "₹18 - 26 LPA", "location": "Remote / Noida / Blr", "role": "SDE", "type": "HealthTech", "url": "https://innovaccer.com/careers/" },
  { "id": 142, "name": "HubSpot", "salary": "₹20 - 35 LPA", "location": "Remote / Hybrid", "role": "SDE", "type": "SaaS", "url": "https://www.hubspot.com/careers" },
  { "id": 143, "name": "DuckDuckGo", "salary": "₹30 - 50 LPA", "location": "Remote", "role": "SDE", "type": "Product", "url": "https://duckduckgo.com/hiring" },
  { "id": 144, "name": "Crossover", "salary": "₹20 - 80 LPA", "location": "Remote", "role": "AI Engineer", "type": "Platform", "url": "https://www.crossover.com/careers" },
  { "id": 145, "name": "Hugging Face", "salary": "₹30 LPA+", "location": "Remote", "role": "ML Research Engineer", "type": "AI", "url": "https://huggingface.co/jobs" },
  { "id": 146, "name": "Weights & Biases", "salary": "₹20 LPA+", "location": "Remote", "role": "AI Developer", "type": "AI", "url": "https://wandb.ai/site/careers" },
  { "id": 147, "name": "Sarvam AI", "salary": "₹15 - 25 LPA", "location": "Bengaluru", "role": "AI Research Engineer", "type": "AI", "url": "https://www.sarvam.ai/" },
  { "id": 148, "name": "Rubrik", "salary": "₹30 - 45 LPA", "location": "Bengaluru", "role": "Software Engineer", "type": "DeepTech", "url": "https://www.rubrik.com/company/careers" },
  { "id": 149, "name": "Cohesity", "salary": "₹25 - 35 LPA", "location": "Bengaluru", "role": "Software Engineer", "type": "DeepTech", "url": "https://www.cohesity.com/company/careers/" },
  { "id": 150, "name": "Nutanix", "salary": "₹20 - 30 LPA", "location": "Bengaluru", "role": "Systems Reliability Eng.", "type": "DeepTech", "url": "https://www.nutanix.com/careers" },
  { "id": 151, "name": "BrowserStack", "salary": "₹18 - 24 LPA", "location": "Bengaluru / Remote", "role": "Software Engineer", "type": "SaaS", "url": "https://www.browserstack.com/careers" },
  { "id": 152, "name": "Udaan", "salary": "₹18 - 24 LPA", "location": "Bengaluru", "role": "SDE", "type": "Product", "url": "https://udaan.com/careers" },
  { "id": 153, "name": "ShareChat", "salary": "₹18 - 26 LPA", "location": "Bengaluru", "role": "SDE", "type": "Product", "url": "https://sharechat.com/careers" },
  { "id": 154, "name": "GoFrugal", "salary": "₹5 - 7 LPA", "location": "Chennai", "role": "MTS", "type": "SaaS", "url": "https://www.gofrugal.com/careers" },
  { "id": 155, "name": "Urjanet (Arcadia)", "salary": "₹5 - 8 LPA", "location": "Chennai", "role": "Data Engineer", "type": "Data", "url": "https://www.arcadia.com/careers" }
];
// samsung,microsoft,rocketlane,latentview,Tiger Analytics,NISSAN MOTOR ,