// logos.js - EXPANDED DOMAIN MAP
const domainMap = {
    // --- FAANG / BIG TECH ---
    "Google": "google.com", "Microsoft": "microsoft.com", "Amazon": "amazon.com",
    "Apple": "apple.com", "Netflix": "netflix.com", "Meta": "meta.com",
    "Facebook": "meta.com", "Adobe": "adobe.com", "Salesforce": "salesforce.com",
    "Oracle": "oracle.com", "Cisco": "cisco.com", "IBM": "ibm.com",
    "Intel": "intel.com", "Nvidia": "nvidia.com", "Samsung": "samsung.com",
    "Uber": "uber.com", "Lyft": "lyft.com", "Airbnb": "airbnb.com",
    "Twitter": "twitter.com", "X": "twitter.com", "LinkedIn": "linkedin.com",
    "Spotify": "spotify.com", "PayPal": "paypal.com", "Intuit": "intuit.com",
    "SAP": "sap.com", "VMware": "vmware.com", "Broadcom": "broadcom.com",
    "Qualcomm": "qualcomm.com", "ServiceNow": "servicenow.com", "Workday": "workday.com",
    "Atlassian": "atlassian.com", "Autodesk": "autodesk.com", "Dell": "dell.com",
    "HP": "hp.com", "AMD": "amd.com", "Texas Instruments": "ti.com",

    // --- INDIAN IT GIANTS (WITCH) ---
    "TCS": "tcs.com", "Tata Consultancy Services": "tcs.com",
    "Infosys": "infosys.com", "Wipro": "wipro.com", "HCL": "hcltech.com",
    "Tech Mahindra": "techmahindra.com", "LTIMindtree": "ltimindtree.com",
    "Cognizant": "cognizant.com", "Capgemini": "capgemini.com",
    "Accenture": "accenture.com", "Mindtree": "ltimindtree.com",
    "Persistent": "persistent.com", "Mphasis": "mphasis.com",
    "Hexaware": "hexaware.com", "KPIT": "kpit.com", "L&T": "ltts.com",

    // --- INDIAN STARTUPS & UNICORNS ---
    "Flipkart": "flipkart.com", "Myntra": "myntra.com", "Meesho": "meesho.io",
    "Swiggy": "swiggy.com", "Zomato": "zomato.com", "Zepto": "zeptonow.com",
    "Blinkit": "blinkit.com", "BigBasket": "bigbasket.com", "Dunzo": "dunzo.com",
    "Ola": "olacabs.com", "Ola Electric": "olaelectric.com", "Rapido": "rapido.bike",
    "Uber India": "uber.com", "Cred": "cred.club", "Paytm": "paytm.com",
    "PhonePe": "phonepe.com", "Razorpay": "razorpay.com", "Groww": "groww.in",
    "Zerodha": "zerodha.com", "Upstox": "upstox.com", "BharatPe": "bharatpe.com",
    "Pine Labs": "pinelabs.com", "BillDesk": "billdesk.com", "PolicyBazaar": "policybazaar.com",
    "Digit Insurance": "godigit.com", "Acko": "acko.com", "Navi": "navi.com",
    "Lenskart": "lenskart.com", "Nykaa": "nykaa.com", "Mamaearth": "mamaearth.in",
    "Purplle": "purplle.com", "Urban Company": "urbancompany.com",
    "NoBroker": "nobroker.in", "MagicBricks": "magicbricks.com",
    "Housing.com": "housing.com", "ShareChat": "sharechat.com",
    "Dailyhunt": "dailyhunt.in", "InMobi": "inmobi.com", "Glance": "glance.com",
    "Dream11": "dream11.com", "MPL": "mpl.live", "Games24x7": "games24x7.com",
    "Nazara": "nazara.com", "PhysicsWallah": "pw.live", "Unacademy": "unacademy.com",
    "Byju's": "byjus.com", "Vedantu": "vedantu.com", "UpGrad": "upgrad.com",
    "Great Learning": "greatlearning.in", "Eruditus": "eruditus.com",
    "Simplilearn": "simplilearn.com", "Scaler": "scaler.com",
    "Oyo": "oyorooms.com", "MakeMyTrip": "makemytrip.com", "Goibibo": "goibibo.com",
    "Yatra": "yatra.com", "Cleartrip": "cleartrip.com", "EaseMyTrip": "easemytrip.com",
    "Ixigo": "ixigo.com", "RedBus": "redbus.in", "Udaan": "udaan.com",
    "Moglix": "moglix.com", "OfBusiness": "ofbusiness.com", "Zetwerk": "zetwerk.com",
    "Infra.Market": "infra.market", "Delhivery": "delhivery.com",
    "Xpressbees": "xpressbees.com", "Shadowfax": "shadowfax.in",
    "Rivigo": "rivigo.com", "BlackBuck": "blackbuck.com", "Porter": "porter.in",
    "Zoho": "zoho.com", "Freshworks": "freshworks.com", "Postman": "postman.com",
    "BrowserStack": "browserstack.com", "Hasura": "hasura.io",
    "Chargebee": "chargebee.com", "Druva": "druva.com", "Icertis": "icertis.com",
    "HighRadius": "highradius.com", "Zenoti": "zenoti.com", "Amagi": "amagi.com",
    "Gupshup": "gupshup.io", "CleverTap": "clevertap.com", "Whatfix": "whatfix.com",
    "MoEngage": "moengage.com", "WebEngage": "webengage.com", "LeadSquared": "leadsquared.com",
    "FarEye": "getfareye.com", "LogiNext": "loginextsolutions.com",
    "Polygon": "polygon.technology", "CoinDCX": "coindcx.com",
    "CoinSwitch": "coinswitch.co", "WazirX": "wazirx.com",

    // --- BANKS / FINTECH (GLOBAL) ---
    "JPMorgan Chase": "jpmorganchase.com", "Goldman Sachs": "goldmansachs.com",
    "Morgan Stanley": "morganstanley.com", "Wells Fargo": "wellsfargo.com",
    "Bank of America": "bankofamerica.com", "Citi": "citi.com",
    "American Express": "americanexpress.com", "Mastercard": "mastercard.us",
    "Visa": "visa.co.in", "Barclays": "barclays.com", "Deutsche Bank": "db.com",
    "UBS": "ubs.com", "Credit Suisse": "credit-suisse.com", "HSBC": "hsbc.com",
    "Standard Chartered": "sc.com", "NatWest": "natwestgroup.com",
    "RBS": "rbs.com", "BNY Mellon": "bnymellon.com", "BlackRock": "blackrock.com",
    "Two Sigma": "twosigma.com", "Jane Street": "janestreet.com",
    "Citadel": "citadel.com", "Hudson River Trading": "hudsonrivertrading.com",
    "Tower Research": "tower-research.com", "DE Shaw": "deshaw.com",
    "Arcesium": "arcesium.com", "WorldQuant": "worldquant.com",
    "Fidelity": "fidelity.com", "Capital One": "capitalone.com",
    "Discover": "discover.com", "Stripe": "stripe.com", "Square": "squareup.com",
    "Block": "block.xyz", "Robinhood": "robinhood.com", "Coinbase": "coinbase.com",
    "Affirm": "affirm.com", "SoFi": "sofi.com", "Chime": "chime.com",
    "Revolut": "revolut.com", "Wise": "wise.com", "Monzo": "monzo.com",
    "N26": "n26.com", "Klarna": "klarna.com", "Adyen": "adyen.com",

    // --- OTHERS / HARDWARE / AUTO ---
    "Siemens": "siemens.com", "Bosch": "bosch.com", "GE": "ge.com",
    "Honeywell": "honeywell.com", "Philips": "philips.com", "Schneider Electric": "se.com",
    "ABB": "abb.com", "Tesla": "tesla.com", "Rivian": "rivian.com",
    "Lucid": "lucidmotors.com", "Ford": "ford.com", "GM": "gm.com",
    "General Motors": "gm.com", "Mercedes": "mercedes-benz.com",
    "BMW": "bmw.com", "Audi": "audi.com", "Volkswagen": "vw.com",
    "Toyota": "toyota.com", "Honda": "honda.com", "Nissan": "nissan-global.com",
    "Renault": "renault.com", "Volvo": "volvocars.com", "Jaguar": "jaguarlandrover.com",
    "Land Rover": "jaguarlandrover.com", "Mahindra": "mahindra.com",
    "Tata Motors": "tatamotors.com", "Bajaj": "bajajauto.com",
    "Hero": "heromotocorp.com", "TVS": "tvsmotor.com", "Royal Enfield": "royalenfield.com",
    "Ather": "atherenergy.com", "Boeing": "boeing.com", "Airbus": "airbus.com",
    "Lockheed Martin": "lockheedmartin.com", "Northrop Grumman": "northropgrumman.com",
    "Raytheon": "rtx.com", "SpaceX": "spacex.com", "Blue Origin": "blueorigin.com",
    "NASA": "nasa.gov", "ISRO": "isro.gov.in"
};