services:
  - type: worker
    name: job-scraper-worker
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: TURSO_ALLJOBS_URL
        sync: false
      - key: TURSO_ALLJOBS_TOKEN
        sync: false
      - key: TURSO_URL
        sync: false
      - key: TURSO_TOKEN
        sync: false
      - key: WEBSHARE_PROXIES
        sync: false
