name = "all-career-api"
main = "src/index.js"
compatibility_date = "2024-04-16"
account_id = "62eacb67a7ee0b199f58ccb540a3eff7"

[[d1_databases]]
binding = "DB"
database_name = "all-career-db"
database_id = "20b71b5c-c070-45b5-9542-27ed1cad89e5"
